# CCA

library(tidyverse)
library(CCA)
library(ggplot2)
library(ggfortify)
library(ggrepel)
library(extrafont)



FTab_data<-read.csv("your species data file")
FTab_data <- with(FTab_data,  FTab_data[order(Location) , ])
abun<-FTab_data[,-(1:5)] #select your data range
row.names(abun)<-FTab_data$Location


env_cca<-read.csv("your environmental data file",check.names=FALSE)
env_cca <- with(env_cca,  env_cca[order(Location) , ])
env<-env_cca [,-1]
row.names(env)<-env_cca$Location


library(vegan)
library(ggvegan)

vare.cca <- cca(abun~., data=env)
s<-summary(vare.cca)

write.csv (s$biplot, "CCAscores.csv")
summary(vare.cca)$cont
plot(vare.cca)

cca_model <-vare.cca
a<-plot(cca_model,choices=c(1,2), display=c('sp','bp'), scaling=2)


#Get CCA scores
df_species  <- data.frame(summary(cca_model)$species[,1:2])# get the species CC1 and CC2 scores
df_sites  <- data.frame(summary(cca_model)$site[,1:2])# get the species CC1 and CC2 scores
df_environ  <- scores(cca_model, display = 'bp') #get the environment vars CC1 and CC2 scores


cca1_varex<-round(summary(cca_model)$cont$importance[2,1]*100,1) #Get percentage of variance explained by first axis
cca2_varex<-round(summary(cca_model)$cont$importance[2,2]*100,1) #Get percentage of variance explained by second axis

#Set a scaling variable to multiply the CCA values, in order to get a very similar plot to the the one generated by plot(cca_model). You can adjust it according to your data
scaling_factor <- 4
geom.text.size = 16


ggplot(df_species, 
       aes(x=CCA1, y=CCA2)) + 
  #Draw lines on x = 0 and y = 0
  geom_hline(yintercept=0, 
             linetype="dashed") +
  geom_vline(xintercept=0, 
             linetype="dashed") +
  # coord_fixed()+
  #Add species text
  geom_point(data=df_species, 
             aes(x=CCA1,#Score in CCA1 to add species text
                 y=CCA2),#Score in CCA2 to add species text
             color = "deepskyblue4")+
  geom_text_repel(data=df_species, cex=6,
                  aes(family="Arial",
                      x=CCA1,#Score in CCA1 to add species text
                      y=CCA2,#Score in CCA2 to add species text
                      label=rownames(df_species)),
                  # hjust=0.01*(1-sign(CCA1)),#Set the text horizontal alignment according to its position in the CCA plot
                  #vjust=-0.5*(1-sign(CCA2))),#Set the text vertical alignment according to its position in the CCA plot
                  color = "forestgreen")+
  #Add sites text
  geom_point(data=df_sites, 
             aes(x=CCA1,#Score in CCA1 to add species text
                 y=CCA2),#Score in CCA2 to add species text
             #color = "blue"
             color = "red"
  )+
  geom_text_repel(data=df_sites, cex=6,
                  aes(family="Arial",
                      x=CCA1,#Score in CCA1 to add species text
                      y=CCA2,#Score in CCA2 to add species text
                      label=rownames(df_sites)),
                  # hjust=-0.01*(1-sign(CCA1)),#Set the text horizontal alignment according to its position in the CCA plot
                  #  vjust=-0.5*(1-sign(CCA2))),#Set the text vertical alignment according to its position in the CCA plot
                  #  color = "blue"
                  color = "red",box.padding = 0.1
  )+
  #Add environmental vars arrows
  geom_segment(data=df_environ, 
               aes(x=0, #Starting coordinate in CCA1 = 0 
                   xend=CCA1*scaling_factor,#Ending coordinate in CCA1  
                   y=0, #Start in CCA2 = 0
                   yend=CCA2*scaling_factor), #Ending coordinate in CCA2 
               color="black", #set color
               arrow=arrow(length=unit(0.01,"npc"))#Set the size of the lines that form the tip of the arrow
  )+
  # Add environmental vars text
  geom_text_repel(data=df_environ,cex =6,
                  aes(family="Arial",
                      x=CCA1*scaling_factor,
                      y=CCA2*scaling_factor,
                      label=rownames(df_environ)),
                  # hjust=0.1*(1-sign(CCA1)),#Add the text of each environmental var at the end of the arrow
                  #  vjust=0.1*(1-sign(CCA2))),#Add the text of each environmental var at the end of the arrow
                  color="black")+
  #Set bw theme
  labs(x=paste0("CCA1 (",cca1_varex," %)"),
       y=paste0("CCA2 (",cca2_varex," %)"))+
  theme(axis.line = element_line(),axis.text=element_text(size=12,family = "arial"),
        axis.title=element_text(size=14,family = "arial",face = "bold"),
        panel.background = element_rect(fill = "white"))
